package(default_visibility = ["//visibility:public"])
cc_proto_library(
    name = "unit_test_cc_proto",
    deps = [
        ":unit_test_proto",
    ],
)

proto_library(
    name = "unit_test_proto",
    srcs = [
        "unit_test.proto",
    ],
)

